name: Compile Examples

on:
  pull_request:
    paths:
      - ".github/workflows/compile-examples.yml"
      - "megaavr/libraries/**"
      - "megaavr/cores/**"
      - "megaavr/variants/**"
  push:
    paths:
      - ".github/workflows/compile-examples.yml"
      - "megaavr/libraries/**"
      - "megaavr/cores/**"
      - "megaavr/variants/**"
  # workflow_dispatch event allows the workflow to be triggered manually
  # See: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#workflow_dispatch
  workflow_dispatch:
  # repository_dispatch event allows the workflow to be triggered via the GitHub API
  # See: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#repository_dispatch
  repository_dispatch:

jobs:
  compile-examples:
    runs-on: ubuntu-latest

    env:
      platform-name: megaTinyCore:megaavr

      available-flash-7_5kB-plus-true-sketch-paths: |
        - megaavr/libraries/EEPROM/examples/eeprom_get
        - megaavr/libraries/USERSIG/examples/usersig_get
        - megaavr/libraries/SPI/examples/BarometricPressureSensor
        - megaavr/libraries/SoftwareSerial/examples/TwoPortReceive
        - megaavr/libraries/Wire/examples/SFRRanger_reader
        - megaavr/libraries/tinyNeoPixel/examples/RGBWstrandtest
      available-flash-4kB-plus-true-sketch-paths: |
        - megaavr/libraries/SoftwareSerial/examples/SoftwareSerialExample
        - megaavr/libraries/Wire/examples/master_reader
      available-flash-3_5kB-plus-true-sketch-paths: |
        - megaavr/libraries/EEPROM/examples/eeprom_crc
        - megaavr/libraries/EEPROM/examples/eeprom_put
        - megaavr/libraries/EEPROM/examples/eeprom_read
        - megaavr/libraries/USERSIG/examples/usersig_crc
        - megaavr/libraries/USERSIG/examples/usersig_put
        - megaavr/libraries/USERSIG/examples/usersig_read
        - megaavr/libraries/Servo/examples/Knob
        - megaavr/libraries/Servo/examples/ServoMaxTest
        - megaavr/libraries/Servo/examples/Sweep
        - megaavr/libraries/Servo_megaTinyCore/examples/Knob
        - megaavr/libraries/Servo_megaTinyCore/examples/ServoMaxTest
        - megaavr/libraries/Servo_megaTinyCore/examples/Sweep
        - megaavr/libraries/Wire/examples/digital_potentiometer
        - megaavr/libraries/Wire/examples/master_writer
        - megaavr/libraries/Wire/examples/slave_receiver
        - megaavr/libraries/megaTinyCore/examples/ModernRevSer
        - megaavr/libraries/megaTinyCore/examples/readTempVcc
        - megaavr/libraries/tinyNeoPixel/examples/buttoncycler
        - megaavr/libraries/tinyNeoPixel/examples/simple
        - megaavr/libraries/tinyNeoPixel/examples/strandtest
        - megaavr/libraries/tinyNeoPixel_Static/examples/buttoncycler
        - megaavr/libraries/tinyNeoPixel_Static/examples/strandtest
      available-flash-2kB-plus-true-sketch-paths: |
        - megaavr/libraries/Wire/examples/slave_sender
      available-flash-1_5kB-plus-true-sketch-paths: |
        - megaavr/libraries/EEPROM/examples/eeprom_clear
        - megaavr/libraries/EEPROM/examples/eeprom_iteration
        - megaavr/libraries/EEPROM/examples/eeprom_update
        - megaavr/libraries/EEPROM/examples/eeprom_write
        - megaavr/libraries/USERSIG/examples/usersig_clear
        - megaavr/libraries/USERSIG/examples/usersig_iteration
        - megaavr/libraries/USERSIG/examples/usersig_update
        - megaavr/libraries/USERSIG/examples/usersig_write
        - megaavr/libraries/Logic/examples/Three_input_AND
        - megaavr/libraries/Logic/examples/Modulate
        - megaavr/libraries/Logic/examples/Oscillate
        - megaavr/libraries/Logic/examples/LatchNoSeq
        - megaavr/libraries/SPI/examples/DigitalPotControl
        - megaavr/libraries/tinyNeoPixel_Static/examples/simple

      IO-class-6-plus-true-sketch-paths: |
        - megaavr/libraries/Logic/examples/Five_input_NOR
      IO-class-2-series-1-sketch-paths: |
        - megaavr/libraries/megaTinyCore/examples/TCA0Demo3

    strategy:
      fail-fast: false

      matrix:
        flash-class:
          - 32
          - 16
          - 8
          - 4
          - 2
        peripheral-class:
          - 2
          - 1
          - 0
        IO-class:
          - 7
          - 6
          - 4
          - 2
        bootloader-code:
          -
          - o

        # Filter out these matrix combinations
        exclude:
          - flash-class: 32
            peripheral-class: 0
          - flash-class: 32
            IO-class: 4
          - flash-class: 32
            IO-class: 2
          - flash-class: 16
            IO-class: 2
          - flash-class: 8
            IO-class: 2
          - flash-class: 4
            peripheral-class: 0
            IO-class: 7
          - flash-class: 2
            IO-class: 7
          - flash-class: 2
            IO-class: 6
          - flash-class: 2
            peripheral-class: 2
          - IO-class: 2
            peripheral-class: 2
          - flash-class: 32
            peripheral-class: 2

        include:
          - flash-class: 32
            bootloader-code:
            available-flash-kB: 32
          - flash-class: 32
            bootloader-code: o
            available-flash-kB: 31.5
          - flash-class: 16
            bootloader-code:
            available-flash-kB: 16
          - flash-class: 16
            bootloader-code: o
            available-flash-kB: 15.5
          - flash-class: 8
            bootloader-code:
            available-flash-kB: 8
          - flash-class: 8
            bootloader-code: o
            available-flash-kB: 7.5
          - flash-class: 4
            bootloader-code:
            available-flash-kB: 4
          - flash-class: 4
            bootloader-code: o
            available-flash-kB: 3.5
          - flash-class: 2
            bootloader-code:
            available-flash-kB: 2
          - flash-class: 2
            bootloader-code: o
            available-flash-kB: 1.5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # See: https://github.com/arduino/compile-sketches/README.md
      - name: Compile examples
        uses: arduino/compile-sketches@main
        with:
          fqbn: ${{ env.platform-name }}:atxy${{ matrix.IO-class }}${{ matrix.bootloader-code }}:chip=${{ matrix.flash-class }}${{ matrix.peripheral-class }}${{ matrix.IO-class }}
          sketch-paths: |
            # It's necessary to jump through some hoops to dynamically generate the env object keys to define the non-universal sketch paths
            # https://docs.github.com/en/free-pro-team@latest/actions/reference/context-and-expression-syntax-for-github-actions#format
            ${{ env[format('available-flash-7_5kB-plus-{0}-sketch-paths', matrix.available-flash-kB >= 7.5)] }}
            ${{ env[format('available-flash-4kB-plus-{0}-sketch-paths', matrix.available-flash-kB >= 4)] }}
            ${{ env[format('available-flash-3_5kB-plus-{0}-sketch-paths', matrix.available-flash-kB >= 3.5)] }}
            ${{ env[format('available-flash-2kB-plus-{0}-sketch-paths', matrix.available-flash-kB >= 2)] }}
            ${{ env[format('available-flash-1_5kB-plus-{0}-sketch-paths', matrix.available-flash-kB >= 1.5)] }}

            ${{ env[format('IO-class-4-plus-{0}-sketch-paths', matrix.IO-class >= 4)] }}
            ${{ env[format('IO-class-{0}-series-{1}-sketch-paths', matrix.IO-class, matrix.peripheral-class)] }}
          platforms: |
            # Install megaTinyCore via Boards Manager for the toolchain
            - source-url: http://drazzy.com/package_drazzy.com_index.json
              name: ${{ env.platform-name }}
            # Overwrite the megaTinyCore release version with the platform from the local path
            - source-path: megaavr
              name: ${{ env.platform-name }}
          libraries: |
            # The sketches don't have any external library dependencies, so just define an empty array
            -
          verbose: false
          enable-deltas-report: true
          enable-warnings-report: true
          sketches-report-path: sketches-reports

      # The report artifact is the mechanism used to pass data to the Report Size Deltas workflow
      - name: Save memory usage change report as artifact
        uses: actions/upload-artifact@v2
        with:
          name: sketches-reports
          path: sketches-reports
