name: Report Size Deltas

on:
  schedule:
    # Check whether any new reports are needed every 5 minutes
    # WARNING: If you run this workflow in a private repo, it will burn through your free GitHub Actions minutes fast!
    #          See https://github.com/arduino/report-size-deltas/README.md for recommended private repo usage option.
    # https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#schedule
    - cron: '*/5 * * * *'

jobs:
  report:
    runs-on: ubuntu-latest

    steps:
      # See: https://github.com/arduino/report-size-deltas/README.md
      - name: Comment size deltas reports to PRs
        uses: arduino/report-size-deltas@main
        with:
          sketches-reports-source: sketches-reports
